sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6DptvwLzkeafrTSLmC
    access-key-secret: QWuwTZLbaVNr4xMFQsEU6KjXljMGNN
    bucket-name: web-study231

  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 0